export interface SummerMatch {
  gameNumber: number
  date: string
  day: number
  location: string
  teams: {
    teamName: string
    playerNum: number // 1 or 2
  }[] // [East, South, West, North]
  finalResults?: {
    playerName: string
    team: string
    wind: "E" | "S" | "W" | "N"
    finalScore: number
    points: number
  }[]
}

export const summerSchedule: SummerMatch[] = [
  // Day 1 - June 15
  {
    gameNumber: 1,
    date: "6月15日",
    day: 1,
    location: "台北",
    teams: [
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 231, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: 150, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "W", finalScore: 188, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 431, points: 0 },
    ],
  },
  {
    gameNumber: 2,
    date: "6月15日",
    day: 1,
    location: "台北",
    teams: [
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "諾亞方舟", wind: "E", finalScore: 198, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: 204, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "W", finalScore: 574, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "N", finalScore: 24, points: 0 },
    ],
  },
  {
    gameNumber: 3,
    date: "6月15日",
    day: 1,
    location: "台北",
    teams: [
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 489, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "S", finalScore: 102, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 168, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "N", finalScore: 241, points: 0 },
    ],
  },
  {
    gameNumber: 4,
    date: "6月15日",
    day: 1,
    location: "東京Ultima",
    teams: [
      { teamName: "影雀", playerNum: 2 },
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "影雀", wind: "E", finalScore: 121, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 331, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 336, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 212, points: 0 },
    ],
  },
  {
    gameNumber: 5,
    date: "6月15日",
    day: 1,
    location: "東京Ultima",
    teams: [
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 498, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 206, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 224, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "N", finalScore: 72, points: 0 },
    ],
  },
  {
    gameNumber: 6,
    date: "6月15日",
    day: 1,
    location: "東京Ultima",
    teams: [
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 169, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "S", finalScore: 366, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "W", finalScore: 123, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "N", finalScore: 342, points: 0 },
    ],
  },
  {
    gameNumber: 7,
    date: "6月15日",
    day: 1,
    location: "東京Rex3",
    teams: [
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "疾風勁草", wind: "E", finalScore: 46, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "S", finalScore: 250, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "W", finalScore: 422, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "N", finalScore: 282, points: 0 },
    ],
  },
  {
    gameNumber: 8,
    date: "6月15日",
    day: 1,
    location: "東京Rex3",
    teams: [
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 276, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "S", finalScore: 141, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: 194, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "N", finalScore: 389, points: 0 },
    ],
  },
  {
    gameNumber: 9,
    date: "6月15日",
    day: 1,
    location: "東京Rex3",
    teams: [
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "諾亞方舟", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 498, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: -71, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 236, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 337, points: 0 },
    ],
  },
  {
    gameNumber: 10,
    date: "6月18日",
    day: 2,
    location: "台北",
    teams: [
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 743, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 377, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: -110, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "N", finalScore: -10, points: 0 },
    ],
  },
  {
    gameNumber: 11,
    date: "6月18日",
    day: 2,
    location: "台北",
    teams: [
      { teamName: "影雀", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "影雀", wind: "E", finalScore: 404, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "S", finalScore: 173, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 198, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 225, points: 0 },
    ],
  },
  {
    gameNumber: 12,
    date: "6月18日",
    day: 2,
    location: "台北",
    teams: [
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 160, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: 205, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "W", finalScore: 209, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 426, points: 0 },
    ],
  },
  {
    gameNumber: 13,
    date: "6月18日",
    day: 2,
    location: "東京Ultima",
    teams: [
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "諾亞方舟", wind: "E", finalScore: 47, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 283, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 321, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "N", finalScore: 349, points: 0 },
    ],
  },
  {
    gameNumber: 14,
    date: "6月18日",
    day: 2,
    location: "東京Ultima",
    teams: [
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 17, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 364, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 203, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 416, points: 0 },
    ],
  },
  {
    gameNumber: 15,
    date: "6月18日",
    day: 2,
    location: "東京Ultima",
    teams: [
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "層層疊", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "疾風勁草", wind: "E", finalScore: 114, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: 571, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: 110, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "N", finalScore: 205, points: 0 },
    ],
  },
  {
    gameNumber: 16,
    date: "6月18日",
    day: 2,
    location: "東京Rex3",
    teams: [
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 130, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: 182, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "W", finalScore: 287, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "N", finalScore: 401, points: 0 },
    ],
  },
  {
    gameNumber: 17,
    date: "6月18日",
    day: 2,
    location: "東京Rex3",
    teams: [
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "疾風勁草", wind: "E", finalScore: 231, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "S", finalScore: 154, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "W", finalScore: 380, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "N", finalScore: 235, points: 0 },
    ],
  },
  {
    gameNumber: 18,
    date: "6月18日",
    day: 2,
    location: "東京Rex3",
    teams: [
      { teamName: "影雀", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "影雀", wind: "E", finalScore: -102, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 393, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "W", finalScore: 270, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 439, points: 0 },
    ],
  },
  {
    gameNumber: 19,
    date: "6月22日",
    day: 3,
    location: "台北",
    teams: [
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "諾亞方舟", wind: "E", finalScore: 467, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: 67, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 161, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "N", finalScore: 305, points: 0 },
    ],
  },
  {
    gameNumber: 20,
    date: "6月22日",
    day: 3,
    location: "台北",
    teams: [
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 395, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 305, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "W", finalScore: 291, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 9, points: 0 },
    ],
  },
  {
    gameNumber: 21,
    date: "6月22日",
    day: 3,
    location: "台北",
    teams: [
      { teamName: "影雀", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "影雀", wind: "E", finalScore: 302, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 151, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: 92, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "N", finalScore: 455, points: 0 },
    ],
  },
  {
    gameNumber: 22,
    date: "6月22日",
    day: 3,
    location: "東京Ultima",
    teams: [
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 538, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "S", finalScore: 295, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "W", finalScore: -24, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 191, points: 0 },
    ],
  },
  {
    gameNumber: 23,
    date: "6月22日",
    day: 3,
    location: "東京Ultima",
    teams: [
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "層層疊", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "諾亞方舟", wind: "E", finalScore: 430, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: 222, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "W", finalScore: 309, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "N", finalScore: 39, points: 0 },
    ],
  },
  {
    gameNumber: 24,
    date: "6月22日",
    day: 3,
    location: "東京Ultima",
    teams: [
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 333, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "S", finalScore: 84, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 157, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "N", finalScore: 426, points: 0 },
    ],
  },
  {
    gameNumber: 25,
    date: "6月22日",
    day: 3,
    location: "東京Rex3",
    teams: [
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "疾風勁草", wind: "E", finalScore: 120, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: 210, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "W", finalScore: 220, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 450, points: 0 },
    ],
  },
  {
    gameNumber: 26,
    date: "6月22日",
    day: 3,
    location: "東京Rex3",
    teams: [
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 342, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: -142, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "W", finalScore: 284, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "N", finalScore: 516, points: 0 },
    ],
  },
  {
    gameNumber: 27,
    date: "6月22日",
    day: 3,
    location: "東京Rex3",
    teams: [
      { teamName: "雙狙人", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 429, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "S", finalScore: 139, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 119, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "N", finalScore: 313, points: 0 },
    ],
  },
  {
    gameNumber: 28,
    date: "6月25日",
    day: 4,
    location: "台北",
    teams: [
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 318, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "S", finalScore: 409, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 9, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "N", finalScore: 264, points: 0 },
    ],
  },
  {
    gameNumber: 29,
    date: "6月25日",
    day: 4,
    location: "台北",
    teams: [
      { teamName: "影雀", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "影雀", wind: "E", finalScore: 121, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 322, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: 233, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 324, points: 0 },
    ],
  },
  {
    gameNumber: 30,
    date: "6月25日",
    day: 4,
    location: "台北",
    teams: [
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 1 },
      { teamName: "影雀", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 160, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "S", finalScore: 41, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "W", finalScore: 341, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 458, points: 0 },
    ],
  },
  {
    gameNumber: 31,
    date: "6月25日",
    day: 4,
    location: "東京Ultima",
    teams: [
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 168, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 326, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "W", finalScore: 138, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 368, points: 0 },
    ],
  },
  {
    gameNumber: 32,
    date: "6月25日",
    day: 4,
    location: "東京Ultima",
    teams: [
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "層層疊", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 462, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 154, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: -4, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 388, points: 0 },
    ],
  },
  {
    gameNumber: 33,
    date: "6月25日",
    day: 4,
    location: "東京Ultima",
    teams: [
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "層層疊", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "疾風勁草", wind: "E", finalScore: 193, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: 412, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: 269, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "N", finalScore: 126, points: 0 },
    ],
  },
  {
    gameNumber: 34,
    date: "6月25日",
    day: 4,
    location: "東京Rex3",
    teams: [
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "諾亞方舟", wind: "E", finalScore: 134, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: 161, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 67, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 638, points: 0 },
    ],
  },
  {
    gameNumber: 35,
    date: "6月25日",
    day: 4,
    location: "東京Rex3",
    teams: [
      { teamName: "鬼點子", playerNum: 2 },
      { teamName: "影雀", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "諾亞方舟", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: -118, points: 0 },
      { playerName: "TBD", team: "影雀", wind: "S", finalScore: 366, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 311, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "N", finalScore: 441, points: 0 },
    ],
  },
  {
    gameNumber: 36,
    date: "6月25日",
    day: 4,
    location: "東京Rex3",
    teams: [
      { teamName: "影雀", playerNum: 2 },
      { teamName: "疾風勁草", playerNum: 2 },
      { teamName: "諾亞方舟", playerNum: 2 },
      { teamName: "鬼點子", playerNum: 2 },
    ],
    finalResults: [
      { playerName: "TBD", team: "影雀", wind: "E", finalScore: 107, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 300, points: 0 },
      { playerName: "TBD", team: "諾亞方舟", wind: "W", finalScore: 405, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 188, points: 0 },
    ],
  },
  // Finals - June 29 & July 2
  {
    gameNumber: 37,
    date: "6月29日",
    day: 5,
    location: "台北直播",
    teams: [
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "雙狙人", wind: "E", finalScore: 330, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "S", finalScore: 235, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "W", finalScore: 296, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "N", finalScore: 139, points: 0 },
    ],
  },
  {
    gameNumber: 38,
    date: "6月29日",
    day: 5,
    location: "台北直播",
    teams: [
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "疾風勁草", wind: "E", finalScore: 335, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "S", finalScore: 389, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "W", finalScore: 76, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "N", finalScore: 200, points: 0 },
    ],
  },
  {
    gameNumber: 39,
    date: "7月2日",
    day: 5,
    location: "台北直播",
    teams: [
      { teamName: "鬼點子", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "層層疊", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "鬼點子", wind: "E", finalScore: 53, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "S", finalScore: 451, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "W", finalScore: 295, points: 0 },
      { playerName: "TBD", team: "層層疊", wind: "N", finalScore: 201, points: 0 },
    ],
  },
  {
    gameNumber: 40,
    date: "7月2日",
    day: 5,
    location: "台北直播",
    teams: [
      { teamName: "層層疊", playerNum: 1 },
      { teamName: "疾風勁草", playerNum: 1 },
      { teamName: "雙狙人", playerNum: 1 },
      { teamName: "鬼點子", playerNum: 1 },
    ],
    finalResults: [
      { playerName: "TBD", team: "層層疊", wind: "E", finalScore: 367, points: 0 },
      { playerName: "TBD", team: "疾風勁草", wind: "S", finalScore: 339, points: 0 },
      { playerName: "TBD", team: "雙狙人", wind: "W", finalScore: 126, points: 0 },
      { playerName: "TBD", team: "鬼點子", wind: "N", finalScore: 168, points: 0 },
    ],
  },
]
